### ISSUE TITLE
Create roadmap.md

### ISSUE THREAD

**Issue by teesloane** [speakfriend/speakfriend#23]
- [x] create roadmap.md
- [x] write introduction detailing how the roadmap is charted (milestones and projects). 
- [x] describe  project ethos
  - [x] address questions on (why aren't you using library / tool / x y z
  - [x] attn simplicity and velocity
  - [x] attn to limited tooling and libraries. 
- [x] outline current milestone  (google form parity).'
- [x] create "down the road / refactors" roadmap.

**Comment by teesloane** [comment]
closed via #25
